In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt#imp lib
import sklearn

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/cpluz-shrijayan/Machine-Learning/main/Multi%20Linear%20Regression/50_Startups.csv")
df.head()#imp dataset

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
#declare x and y
x=df.iloc[:,:4]
y=df.iloc[:,4]

In [4]:
#convert cat col values into num val 
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

In [5]:
encoder_df=pd.DataFrame(encoder.fit_transform(x[['State']]).toarray())
encoder_df

      0    1    2
0   0.0  0.0  1.0
1   1.0  0.0  0.0
2   0.0  1.0  0.0
3   0.0  0.0  1.0
4   0.0  1.0  0.0
5   0.0  0.0  1.0
6   1.0  0.0  0.0
7   0.0  1.0  0.0
8   0.0  0.0  1.0
9   1.0  0.0  0.0
10  0.0  1.0  0.0
11  1.0  0.0  0.0
12  0.0  1.0  0.0
13  1.0  0.0  0.0
14  0.0  1.0  0.0
15  0.0  0.0  1.0
16  1.0  0.0  0.0
17  0.0  0.0  1.0
18  0.0  1.0  0.0
19  0.0  0.0  1.0
20  1.0  0.0  0.0
21  0.0  0.0  1.0
22  0.0  1.0  0.0
23  0.0  1.0  0.0
24  0.0  0.0  1.0
25  1.0  0.0  0.0
26  0.0  1.0  0.0
27  0.0  0.0  1.0
28  0.0  1.0  0.0
29  0.0  0.0  1.0
30  0.0  1.0  0.0
31  0.0  0.0  1.0
32  1.0  0.0  0.0
33  0.0  1.0  0.0
34  1.0  0.0  0.0
35  0.0  0.0  1.0
36  0.0  1.0  0.0
37  1.0  0.0  0.0
38  0.0  0.0  1.0
39  1.0  0.0  0.0
40  1.0  0.0  0.0
41  0.0  1.0  0.0
42  1.0  0.0  0.0
43  0.0  0.0  1.0
44  1.0  0.0  0.0
45  0.0  0.0  1.0
46  0.0  1.0  0.0
47  1.0  0.0  0.0
48  0.0  0.0  1.0
49  1.0  0.0  0.0

In [6]:
_df=x.join(encoder_df)
_df

    R&D Spend  Administration  Marketing Spend       State    0    1    2
0   165349.20       136897.80        471784.10    New York  0.0  0.0  1.0
1   162597.70       151377.59        443898.53  California  1.0  0.0  0.0
2   153441.51       101145.55        407934.54     Florida  0.0  1.0  0.0
3   144372.41       118671.85        383199.62    New York  0.0  0.0  1.0
4   142107.34        91391.77        366168.42     Florida  0.0  1.0  0.0
5   131876.90        99814.71        362861.36    New York  0.0  0.0  1.0
6   134615.46       147198.87        127716.82  California  1.0  0.0  0.0
7   130298.13       145530.06        323876.68     Florida  0.0  1.0  0.0
8   120542.52       148718.95        311613.29    New York  0.0  0.0  1.0
9   123334.88       108679.17        304981.62  California  1.0  0.0  0.0
10  101913.08       110594.11        229160.95     Florida  0.0  1.0  0.0
11  100671.96        91790.61        249744.55  California  1.0  0.0  0.0
12   93863.75       127320.38        249839.44     Florida  0.0  1.0  0.0
13   91992.39       135495.07        252664.93  California  1.0  0.0  0.0
14  119943.24       156547.42        256512.92     Florida  0.0  1.0  0.0
15  114523.61       122616.84        261776.23    New York  0.0  0.0  1.0
16   78013.11       121597.55        264346.06  California  1.0  0.0  0.0
17   94657.16       145077.58        282574.31    New York  0.0  0.0  1.0
18   91749.16       114175.79        294919.57     Florida  0.0  1.0  0.0
19   86419.70       153514.11             0.00    New York  0.0  0.0  1.0
20   76253.86       113867.30        298664.47  California  1.0  0.0  0.0
21   78389.47       153773.43        299737.29    New York  0.0  0.0  1.0
22   73994.56       122782.75        303319.26     Florida  0.0  1.0  0.0
23   67532.53       105751.03        304768.73     Florida  0.0  1.0  0.0
24   77044.01        99281.34        140574.81    New York  0.0  0.0  1.0
25   64664.71       139553.16        137962.62  California  1.0  0.0  0.0
26   75328.87       144135.98        134050.07     Florida  0.0  1.0  0.0
27   72107.60       127864.55        353183.81    New York  0.0  0.0  1.0
28   66051.52       182645.56        118148.20     Florida  0.0  1.0  0.0
29   65605.48       153032.06        107138.38    New York  0.0  0.0  1.0
30   61994.48       115641.28         91131.24     Florida  0.0  1.0  0.0
31   61136.38       152701.92         88218.23    New York  0.0  0.0  1.0
32   63408.86       129219.61         46085.25  California  1.0  0.0  0.0
33   55493.95       103057.49        214634.81     Florida  0.0  1.0  0.0
34   46426.07       157693.92        210797.67  California  1.0  0.0  0.0
35   46014.02        85047.44        205517.64    New York  0.0  0.0  1.0
36   28663.76       127056.21        201126.82     Florida  0.0  1.0  0.0
37   44069.95        51283.14        197029.42  California  1.0  0.0  0.0
38   20229.59        65947.93        185265.10    New York  0.0  0.0  1.0
39   38558.51        82982.09        174999.30  California  1.0  0.0  0.0
40   28754.33       118546.05        172795.67  California  1.0  0.0  0.0
41   27892.92        84710.77        164470.71     Florida  0.0  1.0  0.0
42   23640.93        96189.63        148001.11  California  1.0  0.0  0.0
43   15505.73       127382.30         35534.17    New York  0.0  0.0  1.0
44   22177.74       154806.14         28334.72  California  1.0  0.0  0.0
45    1000.23       124153.04          1903.93    New York  0.0  0.0  1.0
46    1315.46       115816.21        297114.46     Florida  0.0  1.0  0.0
47       0.00       135426.92             0.00  California  1.0  0.0  0.0
48     542.05        51743.15             0.00    New York  0.0  0.0  1.0
49       0.00       116983.80         45173.06  California  1.0  0.0  0.0

In [7]:
_df.drop('State',axis=1,inplace=True)
print(_df)

    R&D Spend  Administration  Marketing Spend    0    1    2
0   165349.20       136897.80        471784.10  0.0  0.0  1.0
1   162597.70       151377.59        443898.53  1.0  0.0  0.0
2   153441.51       101145.55        407934.54  0.0  1.0  0.0
3   144372.41       118671.85        383199.62  0.0  0.0  1.0
4   142107.34        91391.77        366168.42  0.0  1.0  0.0
5   131876.90        99814.71        362861.36  0.0  0.0  1.0
6   134615.46       147198.87        127716.82  1.0  0.0  0.0
7   130298.13       145530.06        323876.68  0.0  1.0  0.0
8   120542.52       148718.95        311613.29  0.0  0.0  1.0
9   123334.88       108679.17        304981.62  1.0  0.0  0.0
10  101913.08       110594.11        229160.95  0.0  1.0  0.0
11  100671.96        91790.61        249744.55  1.0  0.0  0.0
12   93863.75       127320.38        249839.44  0.0  1.0  0.0
13   91992.39       135495.07        252664.93  1.0  0.0  0.0
14  119943.24       156547.42        256512.92  0.0  1.0  0.0
15  114523.61       122616.84        261776.23  0.0  0.0  1.0
16   78013.11       121597.55        264346.06  1.0  0.0  0.0
17   94657.16       145077.58        282574.31  0.0  0.0  1.0
18   91749.16       114175.79        294919.57  0.0  1.0  0.0
19   86419.70       153514.11             0.00  0.0  0.0  1.0
20   76253.86       113867.30        298664.47  1.0  0.0  0.0
21   78389.47       153773.43        299737.29  0.0  0.0  1.0
22   73994.56       122782.75        303319.26  0.0  1.0  0.0
23   67532.53       105751.03        304768.73  0.0  1.0  0.0
24   77044.01        99281.34        140574.81  0.0  0.0  1.0
25   64664.71       139553.16        137962.62  1.0  0.0  0.0
26   75328.87       144135.98        134050.07  0.0  1.0  0.0
27   72107.60       127864.55        353183.81  0.0  0.0  1.0
28   66051.52       182645.56        118148.20  0.0  1.0  0.0
29   65605.48       153032.06        107138.38  0.0  0.0  1.0
30   61994.48       115641.28         91131.24  0.0  1.0  0.0
31   61136.38       152701.92         88218.23  0.0  0.0  1.0
32   63408.86       129219.61         46085.25  1.0  0.0  0.0
33   55493.95       103057.49        214634.81  0.0  1.0  0.0
34   46426.07       157693.92        210797.67  1.0  0.0  0.0
35   46014.02        85047.44        205517.64  0.0  0.0  1.0
36   28663.76       127056.21        201126.82  0.0  1.0  0.0
37   44069.95        51283.14        197029.42  1.0  0.0  0.0
38   20229.59        65947.93        185265.10  0.0  0.0  1.0
39   38558.51        82982.09        174999.30  1.0  0.0  0.0
40   28754.33       118546.05        172795.67  1.0  0.0  0.0
41   27892.92        84710.77        164470.71  0.0  1.0  0.0
42   23640.93        96189.63        148001.11  1.0  0.0  0.0
43   15505.73       127382.30         35534.17  0.0  0.0  1.0
44   22177.74       154806.14         28334.72  1.0  0.0  0.0
45    1000.23       124153.04          1903.93  0.0  0.0  1.0
46    1315.46       115816.21        297114.46  0.0  1.0  0.0
47       0.00       135426.92             0.00  1.0  0.0  0.0
48     542.05        51743.15             0.00  0.0  0.0  1.0
49       0.00       116983.80         45173.06  1.0  0.0  0.0

In [8]:
X=_df
X

    R&D Spend  Administration  Marketing Spend    0    1    2
0   165349.20       136897.80        471784.10  0.0  0.0  1.0
1   162597.70       151377.59        443898.53  1.0  0.0  0.0
2   153441.51       101145.55        407934.54  0.0  1.0  0.0
3   144372.41       118671.85        383199.62  0.0  0.0  1.0
4   142107.34        91391.77        366168.42  0.0  1.0  0.0
5   131876.90        99814.71        362861.36  0.0  0.0  1.0
6   134615.46       147198.87        127716.82  1.0  0.0  0.0
7   130298.13       145530.06        323876.68  0.0  1.0  0.0
8   120542.52       148718.95        311613.29  0.0  0.0  1.0
9   123334.88       108679.17        304981.62  1.0  0.0  0.0
10  101913.08       110594.11        229160.95  0.0  1.0  0.0
11  100671.96        91790.61        249744.55  1.0  0.0  0.0
12   93863.75       127320.38        249839.44  0.0  1.0  0.0
13   91992.39       135495.07        252664.93  1.0  0.0  0.0
14  119943.24       156547.42        256512.92  0.0  1.0  0.0
15  114523.61       122616.84        261776.23  0.0  0.0  1.0
16   78013.11       121597.55        264346.06  1.0  0.0  0.0
17   94657.16       145077.58        282574.31  0.0  0.0  1.0
18   91749.16       114175.79        294919.57  0.0  1.0  0.0
19   86419.70       153514.11             0.00  0.0  0.0  1.0
20   76253.86       113867.30        298664.47  1.0  0.0  0.0
21   78389.47       153773.43        299737.29  0.0  0.0  1.0
22   73994.56       122782.75        303319.26  0.0  1.0  0.0
23   67532.53       105751.03        304768.73  0.0  1.0  0.0
24   77044.01        99281.34        140574.81  0.0  0.0  1.0
25   64664.71       139553.16        137962.62  1.0  0.0  0.0
26   75328.87       144135.98        134050.07  0.0  1.0  0.0
27   72107.60       127864.55        353183.81  0.0  0.0  1.0
28   66051.52       182645.56        118148.20  0.0  1.0  0.0
29   65605.48       153032.06        107138.38  0.0  0.0  1.0
30   61994.48       115641.28         91131.24  0.0  1.0  0.0
31   61136.38       152701.92         88218.23  0.0  0.0  1.0
32   63408.86       129219.61         46085.25  1.0  0.0  0.0
33   55493.95       103057.49        214634.81  0.0  1.0  0.0
34   46426.07       157693.92        210797.67  1.0  0.0  0.0
35   46014.02        85047.44        205517.64  0.0  0.0  1.0
36   28663.76       127056.21        201126.82  0.0  1.0  0.0
37   44069.95        51283.14        197029.42  1.0  0.0  0.0
38   20229.59        65947.93        185265.10  0.0  0.0  1.0
39   38558.51        82982.09        174999.30  1.0  0.0  0.0
40   28754.33       118546.05        172795.67  1.0  0.0  0.0
41   27892.92        84710.77        164470.71  0.0  1.0  0.0
42   23640.93        96189.63        148001.11  1.0  0.0  0.0
43   15505.73       127382.30         35534.17  0.0  0.0  1.0
44   22177.74       154806.14         28334.72  1.0  0.0  0.0
45    1000.23       124153.04          1903.93  0.0  0.0  1.0
46    1315.46       115816.21        297114.46  0.0  1.0  0.0
47       0.00       135426.92             0.00  1.0  0.0  0.0
48     542.05        51743.15             0.00  0.0  0.0  1.0
49       0.00       116983.80         45173.06  1.0  0.0  0.0

In [9]:
#split dataset
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test)=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
x_train.shape

(40, 6)

In [11]:
x_test.shape

(10, 6)

In [12]:
y_train.shape

(40,)

In [13]:
y_test.shape

(10,)

In [14]:
#train using x and y train
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

LinearRegression()

In [15]:
lr.score(x_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

0.8987266414329448

In [16]:
y_pred=lr.predict(x_test)
y_pred

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

array([126362.87908255,  84608.45383633,  99677.49425146,  46357.46068582,
       128750.48288505,  50912.41741878, 109741.35032702, 100643.24281647,
        97599.27574593, 113097.42524431])